version: "3.8"

services:
  app:
    container_name: discord_app
    image: app
    build:
      context: ./app
    volumes:
      - ./app/src:/app/src
    ports:
      - ${APP_PORTS}

  db:
    image: couchdb:${COUCHDB_IMAGE_TAG}
    ports:
      - ${COUCHDB_PORTS}
    volumes:
      - ${COUCHDB_DATA_PATH}:/opt/couchdb/data
    environment:
      - COUCHDB_PASSWORD
      - COUCHDB_USER

  # bot:
  #   container_name: discord_bot
  #   image: bot
  #   build:
  #     context: ./bot
  #     args:
  #       - BOT_TOKEN=${BOT_TOKEN}
  #   volumes:
  #     - ./bot:/bot
  #   ports:
  #     - ${BOT_PORTS}
